<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joel Carroll, Elise Dixon, Paul Hill">

<title>STA5507 - Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Final_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Final_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">STA5507 - Final Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joel Carroll, Elise Dixon, Paul Hill </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><em>Disclaimer: We didn’t use AI tools at all</em></p>
<section id="project-guidelines" class="level1">
<h1>Project Guidelines</h1>
<section id="data-set" class="level2">
<h2 class="anchored" data-anchor-id="data-set">Data set</h2>
<p>The dataset <code>df_who</code> was derived from the World Health Organization (WHO) Life Expectancy dataset, focusing on health indicators and socioeconomic factors that potentially influence life expectancy in developing countries. After data cleaning, transformation, and filtering, ‘df_who’ contains a random sample of size 500 from the original dataset, with each observation representing a year-country combination from the subset of “Developing” countries. Although the sample unit in the original dataset is “country,” for the purposes of this analysis, we assume that the 500 observations are independent.</p>
<p><strong>Variables in</strong> <code>df_who</code><strong>:</strong></p>
<ul>
<li><p><strong>life</strong> <span class="math inline">\(y\)</span>: Life expectancy at birth (in years) - the primary response variable in the analysis, reflecting the average number of years a newborn is expected to live given current health and socioeconomic conditions.</p></li>
<li><p><strong>GDP</strong> <span class="math inline">\(x_1\)</span>: Gross Domestic Product per capita (in USD) - a measure of a country’s economic output per person, indicating overall economic well-being. The variable is represented in its original form, with higher values typically indicating greater economic resources.</p></li>
<li><p><strong>school</strong> <span class="math inline">\(x_2\)</span>: Average years of schooling - an indicator of educational attainment within a country, with more years of schooling generally associated with better health outcomes.</p></li>
<li><p><strong>hiv</strong> <span class="math inline">\(x_3\)</span>: HIV/AIDS prevalence (per 1,000 people) - an indicator of the impact of HIV/AIDS within the population. This variable is provided in its raw form, representing the number of cases per 1,000 people.</p></li>
<li><p><strong>year</strong> <span class="math inline">\(x_4\)</span>: Year (ordered categorical variable) - represents the year the data was collected, enabling temporal trend analysis. This is treated as an ordered factor to respect the time sequence.</p></li>
<li><p><strong>cat_thinness</strong> <span class="math inline">\(x_5\)</span>: Thinness category (ordered categorical variable) - created based on the “thinness (5-9 years)” indicator. It has two levels, grouping countries into thinness categories defined by specific breaks (0-10 and 10-30). The thinness variable refers to the prevalence (i.e., percentage) of children between 5 and 9 years old with low Body Mass Index (BMI). The thinness variable is typically used to assess malnutrition levels across populations.</p></li>
</ul>
</section>
<section id="nonparametric-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="nonparametric-regression-models">Nonparametric regression models</h2>
<p>The aim of this final project is to fit nonparametric regression models with life expectancy as the response variable and a selection of covariates that capture key health and socioeconomic factors. The covariates include the logarithm of GDP, average years of schooling, log of HIV/AIDS prevalence, year (treated as an ordered categorical variable), and thinness category. Through these models, we seek to explore and analyze the relationships between life expectancy and the chosen covariates in developing countries.<br>
Consider the following models:</p>
<ol type="1">
<li><p>Nadaraya-Watson estimator with asymptotic confidence bands.</p></li>
<li><p>Local constant regression with naive bootstrap confidence bands.</p></li>
<li><p>Local linear regression with wild bootstrap confidence bands.</p></li>
<li><p>Generalized additive model (GAM) without including interactions.</p></li>
<li><p>Bayesian additive regression trees (BART).</p></li>
</ol>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data analysis</h2>
<p>In this project, we want to make inferences about</p>
<p><span class="math display">\[
E(Y|X_1=x_1,X_2=x_2,X_3=x_3,X_4=x_4,X_5=x_5)
\]</span>and for each of the models, you need to provide an answer or a solution for the following items:</p>
<ol type="1">
<li><p>Comment on the underlying modeling assumptions and whether or not we can check some of them. Check those that can be verified.</p></li>
<li><p>Using the model outputs, determine how each of the these five predictors relates to the response. Interpret the results in the context of the problem.</p></li>
<li><p>Choose a combination for <span class="math inline">\((x_1,x_2,x_3,x_4,x_5)\)</span>, and provide a point and interval estimate of</p>
<p><span class="math display">\[
E(Y|X_1=x_1,X_2=x_2,X_3=x_3,X_4=x_4,X_5=x_5).
\]</span></p>
<p>Interpret the result in the context of the problem.</p></li>
<li><p>Choose a combination for <span class="math inline">\((x_1,x_2,x_3,x_4,x_5)\)</span> and a value for <span class="math inline">\(\Delta_3\)</span>, and provide a point and interval estimate of</p>
<p><span class="math display">\[
E(Y|X_1=x_1,X_2=x_2,X_3=x_3+\Delta_3,X_4=x_4,X_5=x_5)
\]</span></p>
<p>and</p>
<p><span class="math display">\[
E(Y|X_1=x_1,X_2=x_2,X_3=x_3,X_4=x_4,X_5=x_5).
\]</span></p>
<p>Provide an interpretation in terms of how the expected value changes when <span class="math inline">\(x_3\)</span> is increased by <span class="math inline">\(\Delta_3\)</span> units.</p></li>
<li><p>Choose a combination for <span class="math inline">\((x_1,x_3,x_4)\)</span>, create a plot that displays a point and interval estimate of</p>
<p><span class="math display">\[
x_2\mapsto E(Y|X_1=x_1,X_2=x_2,X_3,X_4=x_4,X_5\in[0,10])
\]</span></p>
<p>and</p>
<p><span class="math display">\[
x_2\mapsto E(Y|X_1=x_1,X_2=x_2,X_3,X_4=x_4,X_5\in(10,30]).
\]</span></p>
<p>Interpret the result in the context of the problem.</p></li>
</ol>
<p><strong>Hint:</strong>&nbsp;When choosing specific values for <span class="math inline">\((x_1,x_2,x_3,x_4,x_5)\)</span>, check that they are not far away from the observed multivariate range.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Require packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(np)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MVN)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Load and prep data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>df_who <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"df_who.csv"</span>)[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df_who[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">=</span> <span class="fu">lapply</span>(df_who[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)   <span class="co">#Order year, thinness</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>df_who[, <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)] <span class="ot">=</span> <span class="fu">lapply</span>(df_who[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)], log)   <span class="co">#Log of GDP, hiv</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_who)[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"log_GDP"</span>, <span class="st">"log_hiv"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Function to plot local constant/local linear regression model outputs</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>model_output <span class="ot">&lt;-</span> <span class="cf">function</span>(bw){</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Fix quantitative predictors to their medians, and categorical            predictors to the most frequent category.</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(df_who<span class="sc">$</span>log_GDP), <span class="fu">median</span>(df_who<span class="sc">$</span>school), <span class="fu">median</span>(df_who<span class="sc">$</span>log_hiv), </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(df_who<span class="sc">$</span>year), <span class="at">decreasing =</span> T))[<span class="dv">1</span>], </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(df_who<span class="sc">$</span>cat_thinness), <span class="at">decreasing =</span> T))[<span class="dv">1</span>])</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Plot mhat vs x[i], i = 1, ..., 5, with other x's fixed</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>){</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">#For quantitative x[i], plot a curve</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(<span class="fu">class</span>(df_who[,i])[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">"numeric"</span>){</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>      n <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>      <span class="co">#Create dataframe of points to evaluate mhat</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      x_seq <span class="ot">=</span> <span class="fu">seq</span>(<span class="fu">min</span>(df_who[,i]), <span class="fu">max</span>(df_who[,i]), </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>                   <span class="at">length.out =</span> n)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>      eval_pts <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, n), <span class="fu">rep</span>(x[<span class="dv">1</span>], n), <span class="fu">rep</span>(x[<span class="dv">2</span>], n), </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">rep</span>(x[<span class="dv">3</span>], n), <span class="fu">rep</span>(x[<span class="dv">4</span>], n), <span class="fu">rep</span>(x[<span class="dv">5</span>], n)),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nrow =</span> n)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>      <span class="fu">colnames</span>(eval_pts) <span class="ot">=</span> <span class="fu">names</span>(df_who)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>      eval_pts[,i] <span class="ot">=</span> x_seq</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>      eval_pts <span class="ot">=</span> <span class="fu">as.data.frame</span>(eval_pts)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>      eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">=</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], as.numeric)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>      eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">=</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>      <span class="co">#Evaluate mhats</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>      mhat <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">exdat =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>      eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> mhat<span class="sc">$</span>mean</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>      <span class="co">#Plot</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>      xlab <span class="ot">=</span> <span class="fu">names</span>(df_who)[i]</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>      title <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"Average Life Expectancy vs"</span>, xlab)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plot</span>(eval_pts[,i], eval_pts<span class="sc">$</span>life, <span class="at">xlab =</span> xlab, <span class="at">ylab =</span> <span class="st">"life"</span>, </span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>           <span class="at">main =</span> title, <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    }<span class="cf">else</span>{</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>      <span class="co">#For categorical x[i], plot points</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>      lvls <span class="ot">=</span> <span class="fu">levels</span>(df_who[,i])</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>      n <span class="ot">=</span> <span class="fu">length</span>(lvls)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>      eval_pts <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, n), <span class="fu">rep</span>(x[<span class="dv">1</span>], n), <span class="fu">rep</span>(x[<span class="dv">2</span>], n), </span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">rep</span>(x[<span class="dv">3</span>], n), <span class="fu">rep</span>(x[<span class="dv">4</span>], n), <span class="fu">rep</span>(x[<span class="dv">5</span>], n)),</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nrow =</span> n)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>      <span class="fu">colnames</span>(eval_pts) <span class="ot">=</span> <span class="fu">names</span>(df_who)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>      eval_pts[,i] <span class="ot">=</span> lvls</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>      eval_pts <span class="ot">=</span> <span class="fu">as.data.frame</span>(eval_pts)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>      eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">=</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], as.numeric)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>      eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">=</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>      <span class="co">#Evaluate points</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>      mhat <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">exdat =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>      eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> mhat<span class="sc">$</span>mean</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>      <span class="co">#Plot</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>      xlab <span class="ot">=</span> <span class="fu">names</span>(df_who)[i]</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>      title <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"Average Life Expectancy vs"</span>, xlab)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plot</span>(eval_pts[,i], eval_pts<span class="sc">$</span>life, <span class="at">xlab =</span> xlab, <span class="at">ylab =</span> <span class="st">"life"</span>, </span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>           <span class="at">main =</span> title, <span class="at">type =</span> <span class="st">"p"</span>)</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="model-1-nadaraya-watson-estimator-with-asymptotic-confidence-bands" class="level1">
<h1>Model 1: Nadaraya-Watson estimator with asymptotic confidence bands</h1>
<p>A popular method of nonparametric regression is kernel regression, which utilizes the fact that the relationship between independent predictors <span class="math inline">\(\vec{X}=(X_1,\ldots,X_p)\)</span> and quantitative response <span class="math inline">\(Y\)</span> can be explained by their joint cumulative distribution function <span class="math inline">\(F\)</span>. Contrary to parametric regression, the general form of a nonparametric regression model</p>
<p><span class="math display">\[
Y = m(\vec X) + \epsilon
\]</span></p>
<p>incorporates a functional component into the parameter space.</p>
<p>Specifically, the conditional probability density function of <span class="math inline">\(f_{Y|\vec{X}=\vec{x}}(y)\)</span> gives us the exact behavior of <span class="math inline">\(Y\)</span> when <span class="math inline">\(\vec{X}=\vec{x}:=(x_1,\ldots,x_p)\)</span>. This conditional pdf, however, is particularly difficult to estimate for given values of each predictor variable. To simplify the problem, we can instead estimate the conditional mean of <span class="math inline">\(Y\)</span> given specific values of <span class="math inline">\(\vec{X}\)</span>, which is a function of <span class="math inline">\(\vec{x}\)</span> defined as</p>
<p><span class="math display">\[
m(\vec{x}):=E[Y|\vec{X}=\vec{x}]=\int_\mathbb{R}yf_{Y|\vec{X}=\vec{x}}(y)dy=\frac{\int_\mathbb{R}yf(\vec{x},y)dy}{f_{\vec{X}}(\vec{x})}
\]</span></p>
<p>where <span class="math inline">\(f\)</span> is the joint pdf/pmf (depending on whether any of the predictor variables are categorical) of the predictors and the response, and <span class="math inline">\(f_{\vec{X}}\)</span> is the marginal probability function of <span class="math inline">\(\vec{X}\)</span>. We can estimate <span class="math inline">\(m\)</span> by replacing <span class="math inline">\(f\)</span> and <span class="math inline">\(f_{\vec{X}}\)</span> with their respective kernel estimates (with given kernels and bandwidths), yielding (after some simplification)</p>
<p><span class="math display">\[
\hat{m}(\vec{x};H)=\sum_{i=1}^n\frac{K_{H}(\vec{x}-\vec{X}_i)}{\sum_{j=1}^nK_{H}(\vec{x}-\vec{X}_j)}Y_i=\sum_{i=1}^nW(\vec{X}_i)Y_i
\]</span></p>
<p>where <span class="math inline">\(K_H\)</span> is the joint kernel estimate of <span class="math inline">\(\vec{X}\)</span> with bandwidth matrix <span class="math inline">\(H\)</span> and</p>
<p><span class="math display">\[
W(\vec{X}_i)=\frac{K_H(\vec{x}-\vec{X}_i)}{\sum_{j=1}^nK_H(\vec{x}-\vec{X}_j)}.
\]</span></p>
<p>This particular estimate of the conditional mean of <span class="math inline">\(Y\)</span> given the predictors is known as the Nadaraya-Watson estimator. We further simplify the problem of estimation by utilizing product kernels so that <span class="math inline">\(K_H(\vec{x}-\vec{X}_i)=\prod_{k=1}^pK_{h_k}(x_k-X_{i,k})\)</span> and <span class="math inline">\(H=\text{diag}(h_1^2,\ldots,h_p^2)\)</span>. For quantitative predictors <span class="math inline">\(X_q\)</span>, we use the Gaussian kernel, and for ordinal predictors <span class="math inline">\(X_d\)</span>, we use the ordered discrete kernel <span class="math inline">\(I_o(x_d-X_d;h_d):=h_d^{|x_d-X_d|}\)</span>. Furthermore, we find the optimal bandwidths <span class="math inline">\(h_1,\ldots,h_p\)</span> that minimize the least-squares cross-validation function</p>
<p><span class="math display">\[
CV(h_1,\ldots,h_p)=\frac{1}{n}\sum_{i=1}^n(Y_i-\hat{m}_{-i}(\vec{X}_i;H))^2
\]</span></p>
<p>where <span class="math inline">\(\hat{m}_{-i}(\vec{x};H)\)</span> is the Nadaraya-Watson estimator of <span class="math inline">\(m(\vec{x})\)</span> using all the data except for <span class="math inline">\(\vec{X}_i\)</span>.</p>
<p>Under certain regularity assumptions, the asymptotic distribution of <span class="math inline">\(\hat{m}(\vec{x};H)\)</span> as <span class="math inline">\(nh\rightarrow\infty\)</span> is normal with mean and variance</p>
<p><span class="math display">\[
E[\hat{m}(\vec{x};H)]=m(\vec{x})+\sum_{k=1}^p\left\{h_k\sigma_{K_{h_k}}^2\left(\frac{\partial^2m}{\partial x_k^2}+\frac{2\frac{\partial m}{\partial x_k}\frac{\partial f_{\vec{X}}}{\partial x_k}}{f_{\vec{X}}(\vec{x})}\right)+o_p(h_k)\right\},
\]</span></p>
<p><span class="math display">\[
\text{Var}(\hat{m}(\vec{x};H))=\frac{\sigma^2(\vec{x})\prod_{k=1}^pR(K_{h_k})}{n\sqrt{|H|}f(\vec{x})}+o_p\left(\left(n\sqrt{|H|}\right)^{-1}\right),
\]</span></p>
<p>respectively. Note that if <span class="math inline">\(h_1,\ldots,h_p\)</span> are small and <span class="math inline">\(m\)</span> is smooth (over the continuous predictors), then the Nadaraya-Watson estimator is close to unbiased. Thus, we can construct a confidence interval for <span class="math inline">\(m\)</span> with standard error</p>
<p><span class="math display">\[
\hat s(\vec{x})=\sqrt{\frac{\hat\sigma^2(\vec{x})\prod_{k=1}^pR(K_{h_k})}{n\sqrt {|H|}\hat f_{\vec{X}}(\vec{x};H)}}
\]</span></p>
<p>where <span class="math inline">\(\hat f_{\vec{X}}(\vec{x};H)\)</span> is the kernel density estimate of <span class="math inline">\(f_{\vec{X}}(\vec{x})\)</span> and <span class="math inline">\(\sigma^2(x_k)\)</span> is estimated by</p>
<p><span class="math display">\[
\hat\sigma^2(\vec{x})=\frac{\sum_{i=1}^nK_H(\vec{x}-\vec{X}_i)(Y_i-\hat m(\vec{x};H))^2}{\sum_{i=1}^nK_{h_k}(x_k-X_{i,k})}
\]</span></p>
<p>to avoid assuming conditional homoscedicity of the residuals. Ultimately, the <span class="math inline">\((1-\alpha/2)\text{%}\)</span> confidence interval for <span class="math inline">\(m\)</span> is given by <span class="math inline">\(\hat m(\vec{x};H)\pm z_{1-\alpha/2}\hat{s}(x)\)</span>.</p>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>The assumptions for a nonparametric model using the Nadaraya-Watson estimator are:</p>
<ol type="1">
<li><p>Around point <span class="math inline">\(\vec X\)</span> the mean of <span class="math inline">\(Y\)</span> can be locally approximated by a constant</p></li>
<li><p>Errors in estimating <span class="math inline">\(Y\)</span> are independent and identically Normally distributed with mean 0 and constant variance</p></li>
<li><p>The unknown function <span class="math inline">\(m\)</span> is twice differentiable with respect to the quantitative predictors</p></li>
<li><p><span class="math inline">\(|H|\)</span> is small while <span class="math inline">\(n|H|\)</span> is large</p></li>
</ol>
<p>Assumption (1) is assumed by the premise of the model, and assumption (3) cannot be verified since <span class="math inline">\(m\)</span> is unknown. Computed bandwidths are relatively small and <span class="math inline">\(n\)</span> is large, reasonably satisfying assumption (4), and requirements of assumption (2) are investigated below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute least-squares cross-validation bandwidth for NW estimator</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">=</span> <span class="fu">npregbw</span>(<span class="at">formula =</span> life <span class="sc">~</span> log_GDP <span class="sc">+</span> school <span class="sc">+</span> log_hiv <span class="sc">+</span> year <span class="sc">+</span> cat_thinness, <span class="at">data =</span> df_who)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check residuals are normal with constant variance</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(df_who)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>mhat <span class="ot">=</span> <span class="fu">npreg</span>(bw)<span class="sc">$</span>mean</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>resids <span class="ot">=</span> mhat <span class="sc">-</span> life</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Check residual plots</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_GDP, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(school, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_hiv, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(year, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cat_thinness, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-3-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check if residuals are multivariate normal given values of quantitative predictors</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>MVN<span class="sc">::</span><span class="fu">mvn</span>(<span class="at">data =</span> <span class="fu">cbind</span>(resids, df_who[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]))<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Test       HZ p value MVN
1 Henze-Zirkler 6.511403       0  NO</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check if residuals are multivariate normal given levels of categorical predictors</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">levels</span>(year)){</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  LF <span class="ot">=</span> <span class="fu">lillie.test</span>(resids[<span class="fu">which</span>(year<span class="sc">==</span>i)])</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lilliefors test of residuals for year"</span>, i, <span class="st">"p-value ="</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>              LF<span class="sc">$</span>p.value))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lilliefors test of residuals for year 2000 p-value = 0.212914443063246"
[1] "Lilliefors test of residuals for year 2001 p-value = 0.432467692154963"
[1] "Lilliefors test of residuals for year 2002 p-value = 0.124076101276831"
[1] "Lilliefors test of residuals for year 2003 p-value = 0.245145510323155"
[1] "Lilliefors test of residuals for year 2004 p-value = 0.0178585760693962"
[1] "Lilliefors test of residuals for year 2005 p-value = 0.00185579497061089"
[1] "Lilliefors test of residuals for year 2006 p-value = 0.00044043428718303"
[1] "Lilliefors test of residuals for year 2007 p-value = 0.117046573335022"
[1] "Lilliefors test of residuals for year 2008 p-value = 0.0372272729709904"
[1] "Lilliefors test of residuals for year 2009 p-value = 0.00111773334501625"
[1] "Lilliefors test of residuals for year 2010 p-value = 0.224350772392553"
[1] "Lilliefors test of residuals for year 2011 p-value = 0.0282175279350592"
[1] "Lilliefors test of residuals for year 2012 p-value = 0.00386431707650081"
[1] "Lilliefors test of residuals for year 2013 p-value = 0.0204726629821187"
[1] "Lilliefors test of residuals for year 2014 p-value = 0.00192917496618653"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">levels</span>(cat_thinness)){</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  LF <span class="ot">=</span> <span class="fu">lillie.test</span>(resids[<span class="fu">which</span>(cat_thinness<span class="sc">==</span>i)])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lilliefors test of residuals for cat_thinness"</span>, i, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>              <span class="st">"p-value ="</span>, LF<span class="sc">$</span>p.value))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lilliefors test of residuals for cat_thinness (0,10] p-value = 3.30443354504891e-09"
[1] "Lilliefors test of residuals for cat_thinness (10,30] p-value = 2.300266788819e-10"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(df_who)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Clearly the verifiable assumptions are not met. Results from the Lilliefors tests suggest the predictors are not normal, and residual plots show nonconstant variance to some degree for all predictors.</p>
</section>
<section id="model-output-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="model-output-and-interpretation">Model output and interpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_output</span>(bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The life expectancy of developing countries fluctuates drastically with respect to the log of GDP. There is a clear positive trend between life expectancy and education, while the log transformed HIV has a negative relationship. Life expectancy dips by year around 2007, perhaps a result of the global economic and housing crisis. Contrary to our intuition, the model suggests life expectancy increases slightly when a larger percentage of the population are malnourished.</p>
</section>
<section id="point-and-interval-estimates" class="level2">
<h2 class="anchored" data-anchor-id="point-and-interval-estimates">Point and interval estimates</h2>
<p>Point and interval estimate of</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>and</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3 + \Delta_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>when <span class="math inline">\((x_1, x_2, x_3, x_4, x_5) = (3000, 10.7, 0.1, 2009, (0,10])\)</span> and <span class="math inline">\(\Delta_3 = 1\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Choose combination of predictor values and change in hiv</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">3000</span>, <span class="fl">10.7</span>, <span class="fl">0.1</span>, <span class="dv">2009</span>, <span class="st">"(0,10]"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span>), </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">school =</span> <span class="fu">rep</span>(x[<span class="dv">2</span>], <span class="dv">2</span>), </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">hiv =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, d)), </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span>), <span class="at">cat_thinness =</span> <span class="fu">rep</span>(x[<span class="dv">5</span>], <span class="dv">2</span>))</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute and display mhat</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>mhat <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">exdat =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">1</span>] <span class="ot">&lt;-</span> mhat<span class="sc">$</span>mean</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>eval_pts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  life_pred      GDP school         hiv year cat_thinness
1  72.37661 8.006368   10.7 -2.30258509 2009       (0,10]
2  69.09870 8.006368   10.7  0.09531018 2009       (0,10]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute and display 95% confidence interval bounds for mhat</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.95</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>z <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.5</span><span class="sc">*</span>alpha)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> mhat<span class="sc">$</span>mean <span class="sc">-</span> z<span class="sc">*</span>mhat<span class="sc">$</span>merr</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> mhat<span class="sc">$</span>mean <span class="sc">+</span> z<span class="sc">*</span>mhat<span class="sc">$</span>merr</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>CI1 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% CI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], <span class="st">", hiv = "</span>, x[<span class="dv">3</span>], <span class="st">", year = "</span>, x[<span class="dv">4</span>], <span class="st">", cat_thinness = "</span>, x[<span class="dv">5</span>], <span class="st">": ("</span>, <span class="fu">floor</span>(LB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>, <span class="fu">ceiling</span>(UB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>CI2 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% CI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], <span class="st">", hiv = "</span>, <span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> d, <span class="st">", year = "</span>, x[<span class="dv">4</span>], <span class="st">", cat_thinness = "</span>, x[<span class="dv">5</span>], <span class="st">": ("</span>, <span class="fu">floor</span>(LB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>, <span class="fu">ceiling</span>(UB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(CI1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI for GDP = 3000, school = 10.7, hiv = 0.1, year = 2009, cat_thinness = (0,10]: (71.01, 73.75)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(CI2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI for GDP = 3000, school = 10.7, hiv = 1.1, year = 2009, cat_thinness = (0,10]: (60.62, 77.57)"</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> Our model predicts that the life expectancy of a country with a per-capita GDP of $3000, an average of 10.7 years of schooling, and an HIV prevalence of 0.1 per 1000 people in the year 2009 with 0-10% of the population between ages 5-9 having a low BMI, is 71.48 years with 95% confidence interval bounds of (70.04, 72.93). Increasing the log of HIV prevalence by 1 results in a predicted life expectancy of 67.23 years with a 95% confidence interval of (64.11, 70.35).</p>
<p>Let <span class="math inline">\((x_1, x_3, x_4) = (3000, 0.1, 2009)\)</span>, create a plot that displays a point and interval estimate of: <span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in [0,10])\]</span> and</p>
<p><span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in (10,30]).\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot mhat vs x2 for fixed x1, x3, and x4 and both levels of x5</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="fu">seq</span>(<span class="fu">min</span>(df_who<span class="sc">$</span>school), <span class="fu">max</span>(df_who<span class="sc">$</span>school), <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(x2)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">school =</span> <span class="fu">rep</span>(x2, <span class="dv">2</span>), <span class="at">hiv =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span><span class="sc">*</span>n), <span class="at">cat_thinness =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"(0,10]"</span>, <span class="st">"(10,30]"</span>), <span class="fu">c</span>(n, n)))</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute mhat</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>mhat <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">exdat =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">1</span>] <span class="ot">&lt;-</span> mhat<span class="sc">$</span>mean</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute 95% confidence bands for mhat</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> mhat<span class="sc">$</span>mean <span class="sc">-</span> z<span class="sc">*</span>mhat<span class="sc">$</span>merr</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> mhat<span class="sc">$</span>mean <span class="sc">+</span> z<span class="sc">*</span>mhat<span class="sc">$</span>merr</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="co">#Display plots</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"Nadaraya-Watson Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with Low Thinness ((0%, 10%])</span><span class="sc">\n</span><span class="st">with Asymptotic Confidence Bands"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">80</span>))</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"Nadaraya-Watson Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with High Thinness ((10%, 30%])</span><span class="sc">\n</span><span class="st">with Asymptotic Confidence Bands"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">80</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> For both levels of thinness, confidence bands vary wildly around 4-9 years of schooling, presumably resulting from these areas having only few observations compared to the other regions of the plots. Regardless, we see a clear upward trend in life expectancy per year of school for each category.</p>
</section>
</section>
<section id="model-2-local-constant-regression-with-naive-bootstrap-confidence-bands" class="level1">
<h1>Model 2: Local constant regression with Naive Bootstrap Confidence Bands</h1>
<p>The Nadaraya-Watson estimator is also known as the local constant regression estimator. Rather than rely on the asymptotic distribution of <span class="math inline">\(\hat m\)</span>, which assumes certain regularity conditions, we can instead estimate its distribution via bootstrapping.</p>
<p>Note that <span class="math inline">\(\hat{m}\)</span> is a function which depends on the data <span class="math inline">\(X=(\vec{X}_1,\ldots,\vec{X}_n)^T\)</span> (where <span class="math inline">\(\vec{X}_i\)</span> is the vector of values of the predictors for the <span class="math inline">\(i^{th}\)</span> observation) and <span class="math inline">\(Y\)</span>. In general, one can obtain a realization of <span class="math inline">\(\hat{m}\)</span> by sampling observations <span class="math inline">\(\vec{X^*_1},\ldots,\vec{X^*_n},\vec{Y^*}\)</span> from the joint distribution <span class="math inline">\(F\)</span> of <span class="math inline">\(X_1,\ldots,X_p,Y\)</span> and computing</p>
<p><span class="math display">\[
\hat{m} (\vec{x}^*;H)=\sum_{i=1}^n W(\vec{X^*_i})Y_i^* \ .
\]</span></p>
<p>Doing so across multiple samples would result in a simulated distribution of <span class="math inline">\(\hat{m}\)</span>. However, since <span class="math inline">\(F\)</span> is often unknown in practice, this approach is unrealistic. A nonparametric solution to this problem is to instead sample <span class="math inline">\(\vec{X^*_1},\ldots,\vec{X^*_n},\vec{Y^*}\)</span> from the empirical joint distribution</p>
<p><span class="math display">\[
\hat{F}_n(\vec{x}, y) := \sum_{i=1}^n \{\mathbb{I}(Y\le y)\prod_{j=1}^p\mathbb{I}(X_j\le x_j)\}
\]</span></p>
<p>(note that this is the same as sampling observations with replacement from the original data). Once we obtain <span class="math inline">\(B\)</span> samples and compute <span class="math inline">\(\hat{m}_b\)</span> for samples <span class="math inline">\(b=1,\ldots,B\)</span>, we can obtain interval bounds from the quantiles of <span class="math inline">\(\hat{m}_1,\ldots,\hat{m}_B\)</span>. Specifically, the lower and upper bounds of the <span class="math inline">\((1-\alpha)\times 100\text{%}\)</span> percentile interval of <span class="math inline">\(\hat{m}\)</span> are the <span class="math inline">\((\alpha/2)^{th}\)</span> and <span class="math inline">\((1-\alpha/2)^{th}\)</span> percentiles of <span class="math inline">\(\hat{m}_1,\ldots,\hat{m}_B\)</span>, respectively.</p>
<section id="assumptions-1" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-1">Assumptions</h2>
<p>This model imposes the same assumptions as model 1, except that there are no regularity conditions on <span class="math inline">\(m\)</span> and there is no requirement that <span class="math inline">\(m\)</span> is twice differentiable with respect to the quantitative predictors; these were needed for the asymptotic distribution of <span class="math inline">\(\hat m\)</span>, but are no longer necessary when we estimate the distribution using bootstrap.</p>
</section>
<section id="model-output-and-interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="model-output-and-interpretation-1">Model output and interpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_output</span>(bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Since the local constant regression estimator is the same as the Nadaraya-Watson estimator, plot outputs and interpretations are the same as before.</p>
</section>
<section id="point-and-interval-estimates-1" class="level2">
<h2 class="anchored" data-anchor-id="point-and-interval-estimates-1">Point and interval estimates</h2>
<p>Point and interval estimate of</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>and</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3 + \Delta_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>when <span class="math inline">\((x_1, x_2, x_3, x_4, x_5) = (3000, 10.7, 0.1, 2009, (0,10])\)</span> and <span class="math inline">\(\Delta_3 = 1\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#NW estimator naive bootstrap function</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>LCR_boot <span class="ot">&lt;-</span> <span class="cf">function</span>(B, n, eval_df){</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  T_n <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="fu">nrow</span>(eval_df), <span class="at">ncol =</span> B)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B){</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Sample observations</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    samp <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df_who), n, <span class="at">replace =</span> T)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    df_samp <span class="ot">=</span> df_who[samp,]</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Obtain estimates based on sampled data</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    life_pred <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">txdat =</span> df_samp[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">tydat =</span> df_samp[,<span class="dv">1</span>], </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">exdat =</span> eval_df[,<span class="sc">-</span><span class="dv">1</span>])<span class="sc">$</span>mean</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    T_n[,b] <span class="ot">=</span> life_pred</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(T_n)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Percentile interval bounds function</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>perc_int <span class="ot">&lt;-</span> <span class="cf">function</span>(T_n, <span class="at">conf_level =</span> <span class="fl">0.95</span>){</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Obtain quantiles</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  alpha_half <span class="ot">=</span> <span class="fl">0.5</span> <span class="sc">-</span> <span class="fl">0.5</span><span class="sc">*</span>conf_level</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>  quants <span class="ot">=</span> <span class="fu">c</span>(alpha_half, <span class="dv">1</span> <span class="sc">-</span> alpha_half)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Obtain bounds based on quantiles</span></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>  n_bounds <span class="ot">=</span> <span class="fu">nrow</span>(T_n)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>  bounds <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> n_bounds, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_bounds){</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>    bounds[i,] <span class="ot">=</span> <span class="fu">quantile</span>(T_n[i,], quants)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(bounds)</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a><span class="co">#Set seed</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20241118</span>)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">log_GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span>), </span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>                       <span class="at">school =</span> <span class="fu">rep</span>(x[<span class="dv">2</span>], <span class="dv">2</span>), </span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>                       <span class="at">log_hiv =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, d)), </span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>                       <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span>), </span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cat_thinness =</span> <span class="fu">rep</span>(x[<span class="dv">5</span>], <span class="dv">2</span>))</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a><span class="co">#Initialize variables</span></span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">1000</span></span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">nrow</span>(df_who)</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a><span class="co">#Perform naive bootstrap</span></span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>mhat_n <span class="ot">=</span> <span class="fu">LCR_boot</span>(B, n, eval_pts)</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> <span class="fu">rowMeans</span>(mhat_n)</span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a>eval_pts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  life_pred  log_GDP school     log_hiv year cat_thinness
1  72.29645 8.006368   10.7 -2.30258509 2009       (0,10]
2  69.27508 8.006368   10.7  0.09531018 2009       (0,10]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute and display 95% percentile interval bounds for mhat</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>bounds <span class="ot">=</span> <span class="fu">perc_int</span>(mhat_n)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> bounds[,<span class="dv">1</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> bounds[,<span class="dv">2</span>]</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>PI1 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% PI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">", hiv = "</span>, x[<span class="dv">3</span>], <span class="st">", year = "</span>, x[<span class="dv">4</span>], <span class="st">", cat_thinness = "</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>            x[<span class="dv">5</span>], <span class="st">": ("</span>, <span class="fu">floor</span>(LB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ceiling</span>(UB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>PI2 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% PI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], <span class="st">", hiv = "</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> d, <span class="st">", year = "</span>, x[<span class="dv">4</span>],</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>            <span class="st">", cat_thinness = "</span>, x[<span class="dv">5</span>], <span class="st">": ("</span>, </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>            <span class="fu">floor</span>(LB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ceiling</span>(UB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(PI1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% PI for GDP = 3000, school = 10.7, hiv = 0.1, year = 2009, cat_thinness = (0,10]: (70.83, 73.79)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(PI2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% PI for GDP = 3000, school = 10.7, hiv = 1.1, year = 2009, cat_thinness = (0,10]: (66.48, 73.06)"</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> life expectancy for a country with a per-capita GDP of $3000, an average of 10.7 years of schooling, and an HIV prevalence of 0.1 per 1000 people in the year 2009 with 0-10% of the population between ages 5-9 having a low BMI, is 71.41 years with 95% confidence interval bounds of (69.31, 73.27). Increasing the log of HIV prevalence by 1 results in a predicted life expectancy of 67.07 years with a 95% confidence interval of (64.26, 69.77). We note the range of the first confidence interval is about the same as the previous model, but the confidence interval after increasing the log of HIV prevalence becomes a bit more precise.</p>
<p>Let <span class="math inline">\((x_1, x_3, x_4) = (3000, 0.1, 2009)\)</span>, create a plot that displays a point and interval estimate of: <span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in [0,10])\]</span> and</p>
<p><span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in (10,30]).\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Set seed</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot mhat vs x2 for fixed x1, x3, and x4 and both levels of x5</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="fu">seq</span>(<span class="fu">min</span>(df_who<span class="sc">$</span>school), <span class="fu">max</span>(df_who<span class="sc">$</span>school), <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(x2)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">school =</span> <span class="fu">rep</span>(x2, <span class="dv">2</span>), <span class="at">hiv =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>                       <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cat_thinness =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"(0,10]"</span>, <span class="st">"(10,30]"</span>), </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                                          <span class="fu">c</span>(n, n)))</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Perform naive bootstrap</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>mhat_n <span class="ot">=</span> <span class="fu">LCR_boot</span>(B, n, eval_pts)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute estimate and 95% percentile bands for life expectancy</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>eval_pts<span class="sc">$</span>life_pred <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">exdat =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>])<span class="sc">$</span>mean</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>bounds <span class="ot">=</span> <span class="fu">perc_int</span>(mhat_n)</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> bounds[,<span class="dv">1</span>]</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> bounds[,<span class="dv">2</span>]</span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a><span class="co">#Display plots</span></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"Nadaraya-Watson Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with Low Thinness ((0%, 10%])</span><span class="sc">\n</span><span class="st">with Naive Bootstrap Percentile Bands"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">quantile</span>(LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="fl">0.1</span>), <span class="fu">quantile</span>(UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="fl">0.9</span>)))</span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"Nadaraya-Watson Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with High Thinness ((10%, 30%])</span><span class="sc">\n</span><span class="st">with Naive Bootstrap Percentile Bands"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">quantile</span>(LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="fl">0.1</span>), <span class="fu">quantile</span>(UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="fl">0.9</span>)))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Confidence interval boundaries are considerably improved from the previous estimates and are now much more meaningful. Bootstrapping the local constant regression estimator significantly outperforms the asymptotic distribution toward producing reasonable margins of error which now provide helpful information in context, as opposed to the previous confidence interval boundaries which relay little to no information in the plots produced. We note that these interval boundaries perform significantly less well at the tails.</p>
</section>
</section>
<section id="model-3-local-linear-regression" class="level1">
<h1>Model 3: Local linear regression</h1>
<p>Local constant regression is a specific case of local polynomial regression, which estimates the conditional mean of <span class="math inline">\(Y\)</span> given a set of values <span class="math inline">\(\vec{x}\)</span> for the predictors <span class="math inline">\(\vec{X}\)</span> according to a weighted average of the observed responses <span class="math inline">\(Y_i\)</span> where the weights are obtained via the kernels at each point of the observed predictors, yielding</p>
<p><span class="math display">\[
W(\vec{X}_i)=\frac{K_H(\vec{x}-\vec{X}_i)}{\sum_{j=1}^nK_H(\vec{x}-\vec{X}_j)}.
\]</span></p>
<p>Another special case of local polynomial regression is local linear regression, which, like the Nadaraya-Watson estimator, seeks to model <span class="math inline">\(m(\vec{x}):=E(Y|\vec{X}=\vec{x})\)</span> via <span class="math inline">\(\hat{m}(\vec{x};H):=\sum_{i=1}^nW(\vec{X}_i)Y_i\)</span>, but uses weights according to</p>
<p><span class="math display">\[
W(\vec{X}_i)=\frac{\frac{1}{n}\sum_{i=1}^n\left\{\left\{\prod_{k=1}^p(x_k-X_{i,k})^2\right\}K_H(\vec{x}-\vec{X}_i)-\left\{\prod_{k=1}^p(x_k-X_{i,k})\right\}\hat{s}_1(\vec{x};H)\right\}}{\hat{s}_2(\vec{x};H)\hat{s}_0(\vec{x};H)-\hat{s}_1(\vec{x};H)}
\]</span></p>
<p>where <span class="math inline">\(\hat{s}_r(\vec{x};H)=\sum_{i=1}^n(\vec{X}_i-\vec{x})^rK_H(\vec{x}-\vec{X}_i)/n\)</span>. Unlike the Nadaraya-Watson estimator of <span class="math inline">\(m\)</span>, the asymptotic distribution of the local linear regression estimator is not as straightforward to derive. Therefore, we estimate its distribution via bootstrapping for the purpose of obtaining confidence bands for our estimate.</p>
<p>Rather than continue to use a naive bootstrap method, we instead use the wild bootstrap. Consider the residuals <span class="math inline">\(\hat\epsilon_i=Y_i-\hat{m}(\vec{x};H)\)</span> (where <span class="math inline">\(\hat{m}\)</span> is now the local linear regression estimator of <span class="math inline">\(m\)</span>). The wild bootstrap residuals are defined as <span class="math inline">\(\epsilon^*_i:=\hat\epsilon_i\tau_i\)</span> where <span class="math inline">\(\tau_1,\ldots,\tau_n\)</span> are i.i.d Rademacher random variables. For each bootstrap <span class="math inline">\(b\)</span>, we obtain <span class="math inline">\((\vec{X^*_1},Y^*_1),\ldots,(\vec{X^*_n},Y^*_n)\)</span> where <span class="math inline">\(\vec{X^*_1},\ldots,\vec{X^*_n}\)</span> are sampled with replacement from the original observations of the predictors and <span class="math inline">\(Y^*_i=\epsilon^*_i+\sum_{i=1}^nW(\vec{X^*_i})Y_i\)</span>, and compute <span class="math inline">\(\hat{m}_b(\vec{x};H):=\sum_{i=1}^nW(\vec{X^*_i})Y^*_i\)</span>. We then use the simulated distribution of <span class="math inline">\(m(\vec{x})\)</span> using <span class="math inline">\(\hat{m}_1(\vec{x};H),\ldots,\hat{m}_B(\vec{x};H)\)</span> where <span class="math inline">\(B\)</span> is the total number of bootstrap iterations.</p>
<section id="assumptions-2" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-2">Assumptions</h2>
<p>The assumptions for a nonparametric model using the local linear regression estimator are:</p>
<ol type="1">
<li><p>Around point <span class="math inline">\(\vec X\)</span> the mean of <span class="math inline">\(Y\)</span> can be locally approximated by a linear function</p></li>
<li><p>Errors in estimating <span class="math inline">\(Y\)</span> are independent and identically Normally distributed with mean 0 and constant variance</p></li>
<li><p><span class="math inline">\(|H|\)</span> is small while <span class="math inline">\(n|H|\)</span> is large</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute least-squares cross-validation bandwidth for local linear estimator</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">npregbw</span>(<span class="at">formula =</span> life <span class="sc">~</span> log_GDP <span class="sc">+</span> school <span class="sc">+</span> log_hiv <span class="sc">+</span> year <span class="sc">+</span> cat_thinness, <span class="at">data =</span> df_who, <span class="at">regtype =</span> <span class="st">"ll"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check residuals are normal with constant variance</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(df_who)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>mhat <span class="ot">=</span> <span class="fu">npreg</span>(bw)<span class="sc">$</span>mean</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>resids <span class="ot">=</span> mhat <span class="sc">-</span> life</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Check residual plots</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_GDP, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(school, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_hiv, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(year, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-11-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cat_thinness, resids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-11-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check if residuals are multivariate normal given values of quantitative predictors</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>MVN<span class="sc">::</span><span class="fu">mvn</span>(<span class="at">data =</span> <span class="fu">cbind</span>(resids, df_who[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]))<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Test       HZ p value MVN
1 Henze-Zirkler 6.519326       0  NO</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check if residuals are multivariate normal given levels of categorical predictors</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">levels</span>(year)){</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  LF <span class="ot">=</span> <span class="fu">lillie.test</span>(resids[<span class="fu">which</span>(year<span class="sc">==</span>i)])</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lilliefors test of residuals for year"</span>, i, <span class="st">"p-value ="</span>, LF<span class="sc">$</span>p.value))</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lilliefors test of residuals for year 2000 p-value = 0.459785688447315"
[1] "Lilliefors test of residuals for year 2001 p-value = 0.316604092547404"
[1] "Lilliefors test of residuals for year 2002 p-value = 0.403407166203053"
[1] "Lilliefors test of residuals for year 2003 p-value = 0.349662948239595"
[1] "Lilliefors test of residuals for year 2004 p-value = 0.0969645465510271"
[1] "Lilliefors test of residuals for year 2005 p-value = 0.137396805467512"
[1] "Lilliefors test of residuals for year 2006 p-value = 0.346721677403117"
[1] "Lilliefors test of residuals for year 2007 p-value = 0.187259214049721"
[1] "Lilliefors test of residuals for year 2008 p-value = 0.252773676403931"
[1] "Lilliefors test of residuals for year 2009 p-value = 0.194292385258702"
[1] "Lilliefors test of residuals for year 2010 p-value = 0.302500097874976"
[1] "Lilliefors test of residuals for year 2011 p-value = 0.135954456614526"
[1] "Lilliefors test of residuals for year 2012 p-value = 0.0404744418302209"
[1] "Lilliefors test of residuals for year 2013 p-value = 0.378430875863033"
[1] "Lilliefors test of residuals for year 2014 p-value = 0.0179817955368328"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">levels</span>(cat_thinness)){</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  LF <span class="ot">=</span> <span class="fu">lillie.test</span>(resids[<span class="fu">which</span>(cat_thinness<span class="sc">==</span>i)])</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lilliefors test of residuals for cat_thinness"</span>, i, <span class="st">"p-value ="</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>              LF<span class="sc">$</span>p.value))</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lilliefors test of residuals for cat_thinness (0,10] p-value = 2.05571842567807e-06"
[1] "Lilliefors test of residuals for cat_thinness (10,30] p-value = 7.99723168375219e-05"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(df_who)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Diagnostic plots show some improvement from prior models toward assumption verification. Residual plots show some clustering, but the assumption of nonconstant variance seems less suspect. Normality tests are also improved, with few significant results from the Lilliefors tests and generally higher p values across the board.</p>
</section>
<section id="model-output-and-interpretation-2" class="level2">
<h2 class="anchored" data-anchor-id="model-output-and-interpretation-2">Model output and interpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_output</span>(bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-12-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-12-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Model output results suggest that the local linear regression estimator does a much better job of recognizing tends in the data while avoiding overfitting the model. The life expectancy of developing countries no longer fluctuates dramatically, but still captures the change in slope around the midregion of the plot. Although there are slight differences to average life expectancy by school and the log of HIV from prior plots, the trends remain mostly the same. However, we note that while the overall shape of average life expectancy by year is likewise similar to previous models, the dip in life expectancy now occurs around the year 2012 as opposed to 2008.</p>
</section>
<section id="point-and-interval-estimates-2" class="level2">
<h2 class="anchored" data-anchor-id="point-and-interval-estimates-2">Point and interval estimates</h2>
<p>Point and interval estimate of</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>and</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3 + \Delta_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>when <span class="math inline">\((x_1, x_2, x_3, x_4, x_5) = (3000, 10.7, 0.1, 2009, (0,10])\)</span> and <span class="math inline">\(\Delta_3 = 1\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Set seed</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20241118</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Local linear regression estimator wild bootstrap function</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>LLR_wild_boot <span class="ot">&lt;-</span> <span class="cf">function</span>(B, n, eval_df){</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Obtain observed residuals</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">=</span> df_who<span class="sc">$</span>life <span class="sc">-</span> <span class="fu">npreg</span>(bw)<span class="sc">$</span>mean</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  T_n <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="fu">nrow</span>(eval_df), <span class="at">ncol =</span> B)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B){</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Sample observations</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>    samp <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df_who), n, <span class="at">replace =</span> T)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    df_samp <span class="ot">=</span> df_who[samp,]</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Obtain wild boostrap residuals</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>    tau <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), n, <span class="at">replace =</span> T)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    et <span class="ot">=</span> e[samp]<span class="sc">*</span>tau</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Obtain simulated life expectancies</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>    life_sim <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">txdat =</span> df_samp[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">tydat =</span> df_samp[,<span class="dv">1</span>])<span class="sc">$</span>mean <span class="sc">+</span> et</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>    df_samp[,<span class="dv">1</span>] <span class="ot">=</span> life_sim</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Obtain estimates based on sampled data and wild bootstrap residuals</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>    life_pred <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">txdat =</span> df_samp[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">tydat =</span> df_samp[,<span class="dv">1</span>], </span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>                      <span class="at">exdat =</span> eval_df[,<span class="sc">-</span><span class="dv">1</span>])<span class="sc">$</span>mean</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>    T_n[,b] <span class="ot">=</span> life_pred</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(T_n)</span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">log_GDP =</span><span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span>), </span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>                       <span class="at">school =</span> <span class="fu">rep</span>(x[<span class="dv">2</span>], <span class="dv">2</span>), </span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>                       <span class="at">hiv =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, d)), </span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a>                       <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span>), </span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cat_thinness =</span> <span class="fu">rep</span>(x[<span class="dv">5</span>], <span class="dv">2</span>))</span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a><span class="co">#Initialize variables</span></span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">1000</span></span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">nrow</span>(df_who)</span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a><span class="co">#Perform naive bootstrap</span></span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a>mhat_n <span class="ot">=</span> <span class="fu">LLR_wild_boot</span>(B, n, eval_pts)</span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> <span class="fu">rowMeans</span>(mhat_n)</span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a>eval_pts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  life_pred  log_GDP school         hiv year cat_thinness
1  70.82389 8.006368   10.7 -2.30258509 2009       (0,10]
2  65.75794 8.006368   10.7  0.09531018 2009       (0,10]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute and display 95% percentile interval bounds for mhat</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>bounds <span class="ot">=</span> <span class="fu">perc_int</span>(mhat_n)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> bounds[,<span class="dv">1</span>]</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> bounds[,<span class="dv">2</span>]</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>PI1 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% CI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">", hiv = "</span>, x[<span class="dv">3</span>], <span class="st">", year = "</span>, x[<span class="dv">4</span>], <span class="st">", cat_thinness = "</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>            x[<span class="dv">5</span>], <span class="st">": ("</span>, <span class="fu">floor</span>(LB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ceiling</span>(UB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>PI2 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% CI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], <span class="st">", hiv = "</span>,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> d, <span class="st">", year = "</span>, x[<span class="dv">4</span>],</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>            <span class="st">", cat_thinness = "</span>, x[<span class="dv">5</span>], <span class="st">": ("</span>, </span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>            <span class="fu">floor</span>(LB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>, </span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ceiling</span>(UB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(PI1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI for GDP = 3000, school = 10.7, hiv = 0.1, year = 2009, cat_thinness = (0,10]: (68.17, 73.56)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(PI2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI for GDP = 3000, school = 10.7, hiv = 1.1, year = 2009, cat_thinness = (0,10]: (63.14, 69.54)"</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> This model predicts that the life expectancy of a country with a per-capita GDP of $3000, an average of 10.7 years of schooling, and an HIV prevalence of 0.1 per 1000 people in the year 2009 with 0-10% of the population between ages 5-9 having a low BMI, is 70.82 years with 95% confidence interval bounds of (68.17, 73.56). Increasing the log of HIV prevalence by 1 results in a predicted life expectancy of 65.76 years with a 95% confidence interval of (63.14, 69.54).</p>
<p>Let <span class="math inline">\((x_1, x_3, x_4) = (3000, 0.1, 2009)\)</span>, create a plot that displays a point and interval estimate of: <span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in [0,10])\]</span> and</p>
<p><span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in (10,30]).\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Set seed</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot mhat vs x2 for fixed x1, x3, and x4 and both levels of x5</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="fu">seq</span>(<span class="fu">min</span>(df_who<span class="sc">$</span>school), <span class="fu">max</span>(df_who<span class="sc">$</span>school), <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(x2)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">school =</span> <span class="fu">rep</span>(x2, <span class="dv">2</span>), <span class="at">hiv =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>                       <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cat_thinness =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"(0,10]"</span>, <span class="st">"(10,30]"</span>), </span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>                                          <span class="fu">c</span>(n, n)))</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Perform naive bootstrap</span></span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>mhat_n <span class="ot">=</span> <span class="fu">LLR_wild_boot</span>(B, n, eval_pts)</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute estimate and 95% confidence bands for life expectancy</span></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>eval_pts<span class="sc">$</span>life_pred <span class="ot">=</span> <span class="fu">npreg</span>(bw, <span class="at">exdat =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>])<span class="sc">$</span>mean</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>bounds <span class="ot">=</span> <span class="fu">perc_int</span>(mhat_n)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> bounds[,<span class="dv">1</span>]</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> bounds[,<span class="dv">2</span>]</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a><span class="co">#Display plots</span></span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"Local Linear Regression Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with Low Thinness ((0%, 10%])</span><span class="sc">\n</span><span class="st">with Wild Bootstrap Percentile Bands"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">quantile</span>(LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="fl">0.1</span>), <span class="fu">quantile</span>(UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="fl">0.9</span>)))</span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"Local Linear Regression Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with High Thinness ((10%, 30%])</span><span class="sc">\n</span><span class="st">with Wild Bootstrap Percentile Bands"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">quantile</span>(LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="fl">0.1</span>), <span class="fu">quantile</span>(UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="fl">0.9</span>)))</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Although the wild bootstrap confidence boundaries perform well throughout the majority of the regression curve, the estimated margins of error are quite wide toward the tails. This likely results from the high concentration of data between 10 to 15 years of school, while data is less dense toward the tails leading to more uncertain interval boundaries.</p>
</section>
</section>
<section id="model-4-generalized-additive-model" class="level1">
<h1>Model 4: Generalized additive model</h1>
<p>In a Generalized Additive Model (referred to as a <em>GAM</em>), we calculate a separate <span class="math inline">\(f_j\)</span> for each <span class="math inline">\(X_j\)</span>, and then add together their contributions without requiring a specific parametric form. This provides a natural extension to the typical multiple linear regression equation:</p>
<p><span class="math display">\[ y_i = \beta_0 + \beta_1X_{i,1} + \dots + \beta_px_{i,p}+\epsilon_i \]</span></p>
<p>in order to allow for non-linear relationships (any smooth <span class="math inline">\(f_j\)</span>) between each feature and the response. We express this extension, the GAM, as:</p>
<p><span class="math display">\[ y_i = \beta_0 + f_j(X_{i,1}) + \dots + fp(x_{i,p})+\epsilon_i. \]</span></p>
<p>Employing GAM’s allows us to work with situations where <span class="math inline">\(Y|X\)</span> is not normal as well as consider the effect of <em>each</em> <span class="math inline">\(X_j\)</span> individually, holding other variables fixed. In this application we will not be including interaction terms.</p>
<section id="assumptions-3" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-3">Assumptions:</h2>
<p>The assumptions of the generalized additive model are:</p>
<ol type="1">
<li><p>At a point <span class="math inline">\(\vec X\)</span>, the mean of <span class="math inline">\(Y\)</span> is a combination of functions of <span class="math inline">\(X_i, i = 1,...,p\)</span></p></li>
<li><p>Functions <span class="math inline">\(f_j\)</span>, fit by the model, should be sufficiently smooth</p></li>
<li><p>Errors in estimating <span class="math inline">\(Y\)</span> are independent and identically Normally distributed with mean 0 and constant variance</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(df_who)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co">#GAM model</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>gam_penalty <span class="ot">&lt;-</span> <span class="fu">gam</span>(life <span class="sc">~</span> <span class="fu">s</span>(log_GDP) <span class="sc">+</span> <span class="fu">s</span>(school) <span class="sc">+</span> <span class="fu">s</span>(log_hiv) </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>                   <span class="sc">+</span> (year) <span class="sc">+</span> (cat_thinness), <span class="at">data =</span> df_who, </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">select =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Check residual plots</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_GDP, gam_penalty<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(school, gam_penalty<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_hiv, gam_penalty<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(year, gam_penalty<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cat_thinness, gam_penalty<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check if residuals are multivariate normal given values of quantitative predictors</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>MVN<span class="sc">::</span><span class="fu">mvn</span>(<span class="at">data =</span> <span class="fu">cbind</span>(gam_penalty<span class="sc">$</span>residuals, df_who[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]))<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Test       HZ p value MVN
1 Henze-Zirkler 7.280789       0  NO</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check if residuals are multivariate normal given levels of categorical predictors</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">levels</span>(year)){</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  LF <span class="ot">=</span> <span class="fu">lillie.test</span>(gam_penalty<span class="sc">$</span>residuals[<span class="fu">which</span>(year<span class="sc">==</span>i)])</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lilliefors test of residuals for year"</span>, i, <span class="st">"p-value ="</span>, LF<span class="sc">$</span>p.value))</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lilliefors test of residuals for year 2000 p-value = 0.512352412632531"
[1] "Lilliefors test of residuals for year 2001 p-value = 0.884382908768735"
[1] "Lilliefors test of residuals for year 2002 p-value = 0.481763300650393"
[1] "Lilliefors test of residuals for year 2003 p-value = 0.0318786062047904"
[1] "Lilliefors test of residuals for year 2004 p-value = 0.0715116064594453"
[1] "Lilliefors test of residuals for year 2005 p-value = 0.0280302394270183"
[1] "Lilliefors test of residuals for year 2006 p-value = 0.695983654249774"
[1] "Lilliefors test of residuals for year 2007 p-value = 0.339918057312396"
[1] "Lilliefors test of residuals for year 2008 p-value = 0.600374591799311"
[1] "Lilliefors test of residuals for year 2009 p-value = 0.0240401552463672"
[1] "Lilliefors test of residuals for year 2010 p-value = 0.0785548908623231"
[1] "Lilliefors test of residuals for year 2011 p-value = 0.712970490164359"
[1] "Lilliefors test of residuals for year 2012 p-value = 0.0944877284883876"
[1] "Lilliefors test of residuals for year 2013 p-value = 0.733077132156978"
[1] "Lilliefors test of residuals for year 2014 p-value = 0.761436793595373"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">levels</span>(cat_thinness)){</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  LF <span class="ot">=</span> <span class="fu">lillie.test</span>(gam_penalty<span class="sc">$</span>residuals[<span class="fu">which</span>(cat_thinness<span class="sc">==</span>i)])</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lilliefors test of residuals for cat_thinness"</span>, i, <span class="st">"p-value ="</span>, </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>              LF<span class="sc">$</span>p.value))</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lilliefors test of residuals for cat_thinness (0,10] p-value = 0.00148014207087106"
[1] "Lilliefors test of residuals for cat_thinness (10,30] p-value = 0.430889725505328"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(df_who)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Model assumptions appear to be reasonably satisfied, as residual plots suggest relatively constant variance toward error terms and results of the Lilliefors normality tests are mostly nonsignificant indicating that predictors, for the most part, can be assumed to be normal. Smoothness of the functions <span class="math inline">\(f_j\)</span> are guaranteed by the packages utilized for analysis.</p>
</section>
<section id="models-output-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="models-output-and-interpretation">Models output and interpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fix quantitative predictors to their medians, and categorical predictors to the most frequent category.</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(df_who<span class="sc">$</span>log_GDP), <span class="fu">median</span>(df_who<span class="sc">$</span>school), <span class="fu">median</span>(df_who<span class="sc">$</span>log_hiv), </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(df_who<span class="sc">$</span>year), <span class="at">decreasing =</span> T))[<span class="dv">1</span>], </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(df_who<span class="sc">$</span>cat_thinness), <span class="at">decreasing =</span> T))[<span class="dv">1</span>])</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot mhat vs x[i], i = 1, ..., 5, with other x's fixed</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>){</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#For quantitative x[i], plot a curve</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">class</span>(df_who[,i])[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">"numeric"</span>){</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>    n <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    x_seq <span class="ot">=</span> <span class="fu">seq</span>(<span class="fu">min</span>(df_who[,i]), <span class="fu">max</span>(df_who[,i]), </span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">length.out =</span> n)</span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>    eval_pts <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, n), <span class="fu">rep</span>(x[<span class="dv">1</span>], n), <span class="fu">rep</span>(x[<span class="dv">2</span>], n), </span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">rep</span>(x[<span class="dv">3</span>], n), <span class="fu">rep</span>(x[<span class="dv">4</span>], n), <span class="fu">rep</span>(x[<span class="dv">5</span>], n)), </span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>                      <span class="at">nrow =</span> n)</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(eval_pts) <span class="ot">&lt;-</span> <span class="fu">names</span>(df_who)</span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>    eval_pts[,i] <span class="ot">=</span> x_seq</span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a>    eval_pts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(eval_pts)</span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a>    eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], as.numeric)</span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a>    eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a>    gampred <span class="ot">=</span> <span class="fu">predict</span>(gam_penalty, <span class="at">newdata =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb67-23"><a href="#cb67-23" aria-hidden="true" tabindex="-1"></a>    eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> gampred<span class="sc">$</span>fit</span>
<span id="cb67-24"><a href="#cb67-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb67-25"><a href="#cb67-25" aria-hidden="true" tabindex="-1"></a>    xlab <span class="ot">=</span> <span class="fu">names</span>(df_who)[i]</span>
<span id="cb67-26"><a href="#cb67-26" aria-hidden="true" tabindex="-1"></a>    title <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"Average Life Expectancy vs"</span>, xlab)</span>
<span id="cb67-27"><a href="#cb67-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(eval_pts[,i], eval_pts<span class="sc">$</span>life, <span class="at">xlab =</span> xlab, <span class="at">ylab =</span> <span class="st">"life"</span>, <span class="at">main =</span> title, </span>
<span id="cb67-28"><a href="#cb67-28" aria-hidden="true" tabindex="-1"></a>         <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb67-29"><a href="#cb67-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb67-30"><a href="#cb67-30" aria-hidden="true" tabindex="-1"></a>  <span class="co">#For categorical x[i], plot points</span></span>
<span id="cb67-31"><a href="#cb67-31" aria-hidden="true" tabindex="-1"></a>  }<span class="cf">else</span>{</span>
<span id="cb67-32"><a href="#cb67-32" aria-hidden="true" tabindex="-1"></a>    lvls <span class="ot">=</span> <span class="fu">levels</span>(df_who[,i])</span>
<span id="cb67-33"><a href="#cb67-33" aria-hidden="true" tabindex="-1"></a>    n <span class="ot">=</span> <span class="fu">length</span>(lvls)</span>
<span id="cb67-34"><a href="#cb67-34" aria-hidden="true" tabindex="-1"></a>    eval_pts <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, n), <span class="fu">rep</span>(x[<span class="dv">1</span>], n), <span class="fu">rep</span>(x[<span class="dv">2</span>], n), </span>
<span id="cb67-35"><a href="#cb67-35" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">rep</span>(x[<span class="dv">3</span>], n), <span class="fu">rep</span>(x[<span class="dv">4</span>], n), <span class="fu">rep</span>(x[<span class="dv">5</span>], n)), </span>
<span id="cb67-36"><a href="#cb67-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">nrow =</span> n)</span>
<span id="cb67-37"><a href="#cb67-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(eval_pts) <span class="ot">&lt;-</span> <span class="fu">names</span>(df_who)</span>
<span id="cb67-38"><a href="#cb67-38" aria-hidden="true" tabindex="-1"></a>    eval_pts[,i] <span class="ot">=</span> lvls</span>
<span id="cb67-39"><a href="#cb67-39" aria-hidden="true" tabindex="-1"></a>    eval_pts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(eval_pts)</span>
<span id="cb67-40"><a href="#cb67-40" aria-hidden="true" tabindex="-1"></a>    eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>], as.numeric)</span>
<span id="cb67-41"><a href="#cb67-41" aria-hidden="true" tabindex="-1"></a>    eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb67-42"><a href="#cb67-42" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb67-43"><a href="#cb67-43" aria-hidden="true" tabindex="-1"></a>    gampred <span class="ot">=</span> <span class="fu">predict</span>(gam_penalty, <span class="at">newdata =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb67-44"><a href="#cb67-44" aria-hidden="true" tabindex="-1"></a>    eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> gampred<span class="sc">$</span>fit</span>
<span id="cb67-45"><a href="#cb67-45" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb67-46"><a href="#cb67-46" aria-hidden="true" tabindex="-1"></a>    xlab <span class="ot">=</span> <span class="fu">names</span>(df_who)[i]</span>
<span id="cb67-47"><a href="#cb67-47" aria-hidden="true" tabindex="-1"></a>    title <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"Average Life Expectancy vs"</span>, xlab)</span>
<span id="cb67-48"><a href="#cb67-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(eval_pts[,i], eval_pts<span class="sc">$</span>life, <span class="at">xlab =</span> xlab, <span class="at">ylab =</span> <span class="st">"life"</span>, <span class="at">main =</span> title, </span>
<span id="cb67-49"><a href="#cb67-49" aria-hidden="true" tabindex="-1"></a>         <span class="at">type =</span> <span class="st">"p"</span>)</span>
<span id="cb67-50"><a href="#cb67-50" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb67-51"><a href="#cb67-51" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-16-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-16-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> For the generalized additive model estimates, we can see that although life expectancy of developing countries still has a positive relationship with the log of GDP, this relationship is now strictly linear, suggesting that prior models could have been slightly overfitting this variable. Similarly, the average life expectancy by school still has a curvilinear relationship but changes in slope are less pronounced. Average life expectancy by year is the most different from other models, suggesting that the relationship between these variables is sporadic and not necessarily captured well by a regression curve. This conclusion is in line with prior model assessments; despite previous models suggesting remotely similar shapes for this pair of variables, the qualities of the curves produced throughout prior analysis had remarkably different qualities; for example, where the minimum fell and if the slope changed sign from positive to negative toward the end region of the plot around 2012-2014.</p>
</section>
<section id="point-and-interval-estimates-3" class="level2">
<h2 class="anchored" data-anchor-id="point-and-interval-estimates-3">Point and interval estimates:</h2>
<p>Point and interval estimate of</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>and</p>
<p><span class="math display">\[ E(Y|X_1 = x_1, X_2 = x_2, X_3 = x_3 + \Delta_3, X_4 = x_4 ,X_5 = x_5) \]</span></p>
<p>when <span class="math inline">\((x_1, x_2, x_3, x_4, x_5) = (3000, 10.7, 0.1, 2009, (0,10])\)</span> and <span class="math inline">\(\Delta_3 = 1\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># combination of (x1:x5)</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">3000</span>, <span class="fl">10.7</span>, <span class="fl">0.1</span>, <span class="dv">2009</span>, <span class="st">"(0,10]"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">log_GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span>), </span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">school =</span> <span class="fu">rep</span>(x[<span class="dv">2</span>], <span class="dv">2</span>), </span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">log_hiv =</span> <span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, d)), </span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span>), <span class="at">cat_thinness =</span> <span class="fu">rep</span>(x[<span class="dv">5</span>], <span class="dv">2</span>))</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a><span class="co"># predict using penalized GAM</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>gampred <span class="ot">&lt;-</span> <span class="fu">predict</span>(gam_penalty, <span class="at">newdata =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">1</span>] <span class="ot">=</span> gampred<span class="sc">$</span>fit</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a>eval_pts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  life_pred  log_GDP school     log_hiv year cat_thinness
1  71.23645 8.006368   10.7 -2.30258509 2009       (0,10]
2  67.19971 8.006368   10.7  0.09531018 2009       (0,10]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> gampred<span class="sc">$</span>fit <span class="sc">-</span> z <span class="sc">*</span> gampred<span class="sc">$</span>se.fit</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> gampred<span class="sc">$</span>fit <span class="sc">+</span> z <span class="sc">*</span> gampred<span class="sc">$</span>se.fit</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co"># point estimate and confidence intervals</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="co">#cat("Point Estimate:", gampred$fit, "\n")</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a><span class="co">#cat("95% Interval Estimate: (", gampred$fit - z * gampred$se.fit, ",",  gampred$fit + z * gampred$se.fit, ")", "\n")</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>CI1 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% CI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], </span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">", hiv = "</span>, x[<span class="dv">3</span>], <span class="st">", year = "</span>, x[<span class="dv">4</span>], <span class="st">", cat_thinness = "</span>,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>            x[<span class="dv">5</span>], <span class="st">": ("</span>, <span class="fu">floor</span>(LB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>,</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ceiling</span>(UB[<span class="dv">1</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>CI2 <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"95% CI for GDP = "</span>, x[<span class="dv">1</span>], <span class="st">", school = "</span>, x[<span class="dv">2</span>], <span class="st">", hiv = "</span>,</span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">as.numeric</span>(x[<span class="dv">3</span>]) <span class="sc">+</span> d, <span class="st">", year = "</span>, x[<span class="dv">4</span>],</span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>            <span class="st">", cat_thinness = "</span>, x[<span class="dv">5</span>], <span class="st">": ("</span>, </span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>            <span class="fu">floor</span>(LB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">", "</span>, </span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ceiling</span>(UB[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">100</span>)<span class="sc">/</span><span class="dv">100</span>, <span class="st">")"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(CI1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI for GDP = 3000, school = 10.7, hiv = 0.1, year = 2009, cat_thinness = (0,10]: (69.93, 72.54)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(CI2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% CI for GDP = 3000, school = 10.7, hiv = 1.1, year = 2009, cat_thinness = (0,10]: (65.75, 68.65)"</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>This model suggests that the life expectancy of a country with a per-capita GDP of $3000, an average of 10.7 years of schooling, and an HIV prevalence of 0.1 per 1000 people in the year 2009 with 0-10% of the population between ages 5-9 having a low BMI, is 71.24 years with 95% confidence interval bounds of (69.93, 72.54). Increasing the log of HIV prevalence by 1 results in a predicted life expectancy of 67.2 years with a 95% confidence interval of (65.75, 68.65). The interval estimate implies that if we sampled 100 developing countries in 2005 with the above observed variables, 95 would have life expediencies at birth between 65.75 and 68.65 years.</p>
<p>Let <span class="math inline">\((x_1, x_3, x_4) = (3000, 2, 2005)\)</span>, create a plot that displays a point and interval estimate of: <span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in [0,10])\]</span> and</p>
<p><span class="math display">\[x_2 \mapsto E(Y \mid X_1 = x_1, X_2 = x_2, X_3, X_4 = x_4, X_5 \in (10,30]).\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot mhat vs x2 for fixed x1, x3, and x4 and both levels of x5</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="fu">seq</span>(<span class="fu">min</span>(df_who<span class="sc">$</span>school), <span class="fu">max</span>(df_who<span class="sc">$</span>school), <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(x2)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Create data frame of points for which the conditional mean will be estimated</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>eval_pts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">life_pred =</span> <span class="cn">NA</span>, <span class="at">log_GDP =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">1</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">school =</span> <span class="fu">rep</span>(x2, <span class="dv">2</span>), <span class="at">log_hiv =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="fu">as.numeric</span>(x[<span class="dv">3</span>])), <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">year =</span> <span class="fu">rep</span>(x[<span class="dv">4</span>], <span class="dv">2</span><span class="sc">*</span>n), </span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">cat_thinness =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"(0,10]"</span>, <span class="st">"(10,30]"</span>), </span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>                                          <span class="fu">c</span>(n, n)))</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>], as.numeric)</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(eval_pts[,<span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>], as.ordered)</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute estimate and 95% confidence bands for life expectancy</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>gampred <span class="ot">&lt;-</span> <span class="fu">predict</span>(gam_penalty, <span class="at">newdata =</span> eval_pts[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>eval_pts<span class="sc">$</span>life_pred <span class="ot">=</span> gampred<span class="sc">$</span>fit</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">=</span> gampred<span class="sc">$</span>fit <span class="sc">-</span> z <span class="sc">*</span> gampred<span class="sc">$</span>se.fit</span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">=</span> gampred<span class="sc">$</span>fit <span class="sc">+</span> z <span class="sc">*</span> gampred<span class="sc">$</span>se.fit</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Display plots</span></span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"GAM Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with Low Thinness ((0%, 10%])"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">quantile</span>(LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="fl">0.1</span>), <span class="fu">quantile</span>(UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="fl">0.9</span>)))</span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[<span class="dv">1</span><span class="sc">:</span>n], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2, eval_pts<span class="sc">$</span>life_pred[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"maroon"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">"Avg Yrs of Schooling"</span>, <span class="at">ylab =</span> <span class="st">"Life Expectancy"</span>, <span class="at">main =</span> <span class="st">"GAM Estimator of Life Expectancy</span><span class="sc">\n</span><span class="st">by Average Number of Years of Schooling</span><span class="sc">\n</span><span class="st">for Nations with High Thinness ((10%, 30%])"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">quantile</span>(LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="fl">0.1</span>), <span class="fu">quantile</span>(UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="fl">0.9</span>)))</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, LB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x2, UB[(n<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>n)], <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>The first plot illustrates that for developing countries in 2005 with:</p>
<ul>
<li><p>Gross Domestic Product per capita is $3000</p></li>
<li><p>0.1 HIV cases per 1,000 people</p></li>
<li><p><strong><em>a thinness indicator (low BMI in children 5-9 years of age) of (0,10]</em></strong></p></li>
</ul>
<p>We can expect the predicted life expectancy at birth to increase from approximately 65 to approximately 80 years as average years in schooling increase within its observed range. The rate of increase can be seen in the plot. The plot also displays a 95% confidence band about the plot.</p>
<p>The second plot illustrates that for developing countries in 2005 with:</p>
<ul>
<li><p>Gross Domestic Product per capita is $3000</p></li>
<li><p>0.1 HIV cases per 1,000 people</p></li>
<li><p><strong><em>a thinness indicator (low BMI in children 5-9 years of age) of (10,30]</em></strong></p></li>
</ul>
<p>We can expect the predicted life expectancy at birth to increase from approximately 62 to approximately 80 years as average years in schooling increase within its observed range. This plot shows a 95% confidence band as well.</p>
<p>A point of interest is that the function has visibly shifted downwards, showing an overall decrease in life expected as the thinness category takes its higher value. In context of the problem, a<em>s a country exhibits a higher rate of children aged 5-9 with low BMI’s, the life expectancy drops at all average years in schooling</em>.</p>
</section>
</section>
<section id="model-5-bayesian-additive-regression-trees" class="level1">
<h1>Model 5: Bayesian additive regression trees</h1>
<p>The Bayesian additive regression trees model is…</p>
<section id="assumptions-4" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-4">Assumptions</h2>
<p>The assumptions are… We can verify the assumption of… by looking at…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Assumption verifications (if needed)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="model-output-and-interpretation-3" class="level2">
<h2 class="anchored" data-anchor-id="model-output-and-interpretation-3">Model output and interpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Obtain fitted model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretation:</strong> …</p>
</section>
<section id="point-and-interval-estimates-4" class="level2">
<h2 class="anchored" data-anchor-id="point-and-interval-estimates-4">Point and interval estimates</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Obtain point/interval estimates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretation:</strong> …</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>